package com.librarysaas.admin.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * What the product owner supplies to onboard a new customer.
 *
 * There is deliberately no password field. The initial password is generated by
 * the server, so it is never typed, never travels in a request body, and never
 * reaches a browser history, proxy log or client-side form state.
 *
 * The organization and library codes are optional. Both columns are NOT NULL and
 * unique in the schema, so a code always exists; when one is not supplied it is
 * derived from the name and returned in the response, which keeps the form to
 * the handful of facts the product owner actually knows about the customer.
 *
 * Every constraint here mirrors the one already enforced by the request objects
 * of the services this composes, so a value accepted here is accepted there.
 */
public class CustomerOnboardingRequest {

    @NotBlank(message = "Organization name is required")
    @Size(max = 200, message = "Organization name must not exceed 200 characters")
    private String organizationName;

    @Size(max = 50, message = "Organization code must not exceed 50 characters")
    @Pattern(regexp = "^[A-Za-z0-9_-]+$",
            message = "Organization code must contain only letters, digits, hyphen or underscore")
    @Schema(description = "Optional. Derived from the organization name when omitted.")
    private String organizationCode;

    @NotBlank(message = "Library name is required")
    @Size(max = 200, message = "Library name must not exceed 200 characters")
    private String libraryName;

    @Size(max = 50, message = "Library code must not exceed 50 characters")
    @Pattern(regexp = "^[A-Za-z0-9_-]+$",
            message = "Library code must contain only letters, digits, hyphen or underscore")
    @Schema(description = "Optional. Derived from the library name when omitted.")
    private String libraryCode;

    @Size(max = 50, message = "Timezone must not exceed 50 characters")
    @Schema(description = "IANA zone id, e.g. Asia/Kolkata. Defaults to the library default when omitted. "
            + "Drives every daily figure the reporting module produces for this library.")
    private String timezone;

    @NotBlank(message = "Administrator username is required")
    @Size(max = 100, message = "Username must not exceed 100 characters")
    @Pattern(regexp = "^[A-Za-z0-9._-]+$",
            message = "Username must contain only letters, digits, dot, hyphen or underscore")
    private String adminUsername;

    @NotBlank(message = "Administrator email is required")
    @Email(message = "Email must be a well-formed email address")
    @Size(max = 150, message = "Email must not exceed 150 characters")
    private String adminEmail;

    @NotBlank(message = "Administrator first name is required")
    @Size(max = 100, message = "First name must not exceed 100 characters")
    private String adminFirstName;

    @Size(max = 100, message = "Last name must not exceed 100 characters")
    private String adminLastName;

    @Size(max = 30, message = "Mobile must not exceed 30 characters")
    @Pattern(regexp = "^[0-9+][0-9 ()-]{5,19}$", message = "Mobile must be a valid contact number")
    private String adminMobile;

    public String getOrganizationName() {
        return organizationName;
    }

    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    public String getOrganizationCode() {
        return organizationCode;
    }

    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode;
    }

    public String getLibraryName() {
        return libraryName;
    }

    public void setLibraryName(String libraryName) {
        this.libraryName = libraryName;
    }

    public String getLibraryCode() {
        return libraryCode;
    }

    public void setLibraryCode(String libraryCode) {
        this.libraryCode = libraryCode;
    }

    public String getTimezone() {
        return timezone;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    public String getAdminUsername() {
        return adminUsername;
    }

    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername;
    }

    public String getAdminEmail() {
        return adminEmail;
    }

    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }

    public String getAdminFirstName() {
        return adminFirstName;
    }

    public void setAdminFirstName(String adminFirstName) {
        this.adminFirstName = adminFirstName;
    }

    public String getAdminLastName() {
        return adminLastName;
    }

    public void setAdminLastName(String adminLastName) {
        this.adminLastName = adminLastName;
    }

    public String getAdminMobile() {
        return adminMobile;
    }

    public void setAdminMobile(String adminMobile) {
        this.adminMobile = adminMobile;
    }
}
